/*
===============================================================
Author: Andrei Dumitru
Created: 2022-11-01
Name: usp_InitializeIncrementalLoad
Description:	 
   
===============================================================
Change History

Date        Name            Description
2022-11-01  Andrei Dumitru  Initial create
2023-11-01  Darren Price    Brought inline with data standards
===============================================================
*/
CREATE PROCEDURE [ETL].[usp_InitializeIncrementalLoad]
    @SOURCE_SYSTEM VARCHAR(250),
    @DATABASE_NAME VARCHAR(250),
    @SCHEMA_NAME VARCHAR(250),
    @TABLE_NAME VARCHAR(250),
    @INCREMENTAL_LOAD_TYPE VARCHAR(100),
    @SYS_CHANGE_VERSION_VALUE VARCHAR(250) NULL,
    @WATERMARK_FIELD VARCHAR(100) NULL,
    @WATERMARK_VALUE VARCHAR(100) NULL
AS
DECLARE @OBJECT_NAME VARCHAR(250);
SET @OBJECT_NAME = CONCAT(REPLACE(REPLACE(REPLACE(@SOURCE_SYSTEM,'.','_'), '-','_'), '\', '_'), '_',@DATABASE_NAME,'_', @SCHEMA_NAME, '_',@TABLE_NAME);

BEGIN
    IF @INCREMENTAL_LOAD_TYPE = 'CHANGE_TRACKING'
    BEGIN
        IF NOT EXISTS (SELECT * FROM ETL.SourceIncrementalLoad WHERE OBJECT_NAME = @OBJECT_NAME )
        INSERT INTO ETL.SourceIncrementalLoad (OBJECT_NAME, SOURCE_SYSTEM, DATABASE_NAME, SCHEMA_NAME, TABLE_NAME,LOAD_TYPE, SYS_CHANGE_VERSION_VALUE)
        VALUES (@OBJECT_NAME, @SOURCE_SYSTEM, @DATABASE_NAME, @SCHEMA_NAME, @TABLE_NAME,@INCREMENTAL_LOAD_TYPE , @SYS_CHANGE_VERSION_VALUE)
    END

    ELSE IF @INCREMENTAL_LOAD_TYPE = 'HIGH_WATERMARK'
    BEGIN
        IF NOT EXISTS (SELECT * FROM ETL.SourceIncrementalLoad WHERE OBJECT_NAME = @OBJECT_NAME )
        INSERT INTO ETL.SourceIncrementalLoad (OBJECT_NAME, SOURCE_SYSTEM, DATABASE_NAME, SCHEMA_NAME, TABLE_NAME,LOAD_TYPE, WATERMARK_FIELD,WATERMARK_VALUE)
        VALUES (@OBJECT_NAME, @SOURCE_SYSTEM, @DATABASE_NAME, @SCHEMA_NAME, @TABLE_NAME,@INCREMENTAL_LOAD_TYPE , @WATERMARK_FIELD, @WATERMARK_VALUE)
    END

    ELSE IF @INCREMENTAL_LOAD_TYPE = 'FULL_LOAD'
    BEGIN
    IF NOT EXISTS (SELECT * FROM ETL.SourceIncrementalLoad WHERE OBJECT_NAME = @OBJECT_NAME )
        INSERT INTO ETL.SourceIncrementalLoad (OBJECT_NAME, SOURCE_SYSTEM, DATABASE_NAME, SCHEMA_NAME, TABLE_NAME,LOAD_TYPE)
        VALUES (@OBJECT_NAME, @SOURCE_SYSTEM, @DATABASE_NAME, @SCHEMA_NAME, @TABLE_NAME,@INCREMENTAL_LOAD_TYPE)
    END
END;