CREATE TABLE [ETL].[JsonMetadata] (
    [OBJECT_ID]         INT           IDENTITY (1, 1) NOT NULL,
    [OBJECT_NAME]       VARCHAR (500) NOT NULL,
    [OBJECT_TYPE]       VARCHAR (100) NOT NULL,
    [PIPELINE_NAME]     VARCHAR (500) NOT NULL,
    [TRIGGERS_INFO]     VARCHAR (MAX) NOT NULL,
    [BATCH_FREQUENCY]   VARCHAR (100) NOT NULL,
    [LOAD_TYPE]         VARCHAR (500) NOT NULL,
    [ADLS_PATHS]        VARCHAR (MAX) NOT NULL,
    [OBJECT_PARAMETERS] VARCHAR (MAX) NOT NULL,
    PRIMARY KEY CLUSTERED ([OBJECT_NAME] ASC)
);