CREATE TABLE [ETL].[Log] (
    [LOG_ID]                         INT            IDENTITY (1, 1) NOT NULL,
    [SOURCE_TYPE]                    VARCHAR (500)  NULL,
    [SOURCE_SYSTEM]                  VARCHAR (500)  NULL,
    [SOURCE_GROUPING_ID]             INT            NULL,
    [OBJECT_NAME]                    VARCHAR (500)  NULL,
    [DATABASE_NAME]                  VARCHAR (500)  NULL,
    [SCHEMA_NAME]                    VARCHAR (500)  NULL,
    [TABLE_NAME]                     VARCHAR (500)  NULL,
    [TRIGGER_TIME]                   DATETIME       NOT NULL,
    [TRIGGER_TYPE]                   VARCHAR (100)  NOT NULL,
    [PIPELINE_RUN_ID]                VARCHAR (500)  NOT NULL,
    [PIPELINE_NAME]                  VARCHAR (500)  NOT NULL,
    [TRIGGERING_PIPELINE_RUN_ID]     VARCHAR (500)  NULL,
    [TRIGGERING_PIPELINE_NAME]       VARCHAR (500)  NULL,
    [OPERATION]                      VARCHAR (500)  NULL,
    [COMPONENT_NAME]                 VARCHAR (500)  NULL,
    [TARGET_SYSTEM]                  VARCHAR (500)  NULL,
    [START_TIME]                     DATETIME2 (0)  NULL,
    [END_TIME]                       DATETIME2 (0)  NULL,
    [DURATION_SECONDS]               INT            NULL,
    [INSERTS]                        INT            NULL,
    [UPDATES]                        INT            NULL,
    [DELETES]                        INT            NULL,
    [ERROR_MESSAGE]                  VARCHAR (4000) NULL,
    [NEW_INCREMENTAL_KEY_VALUE]      VARCHAR (500)  NULL,
    [PREVIOUS_INCREMENTAL_KEY_VALUE] VARCHAR (500)  NULL
);

