CREATE TABLE [ETL].[Log] (
    [LOG_ID]                INT            IDENTITY (1, 1) NOT NULL,
    [TRIGGER_NAME]          VARCHAR (500)  NOT NULL,
    [TRIGGER_TIME]          DATETIME       NOT NULL,
    [TRIGGER_TYPE]          VARCHAR (100)  NOT NULL,
    [PIPELINE_RUN_ID]       VARCHAR (500)  NOT NULL,
    [PIPELINE_NAME]         VARCHAR (500)  NOT NULL,
    [COMPONENT_NAME]        VARCHAR (500)  NOT NULL,
    [SOURCE_SYSTEM]         VARCHAR (500)  NULL,
    [TARGET_SYSTEM]         VARCHAR (500)  NULL,
    [SCHEMA_NAME]           VARCHAR (500)  NULL,
    [TABLE_NAME]            VARCHAR (500)  NULL,
    [OPERATION]             VARCHAR (500)  NULL,
    [START_TIME]            DATETIME2 (0)  NULL,
    [END_TIME]              DATETIME2 (0)  NULL,
    [DURATION_SECONDS]      INT            NULL,
    [INSERTS]               INT            NULL,
    [UPDATES]               INT            NULL,
    [DELETES]               INT            NULL,
    [ERROR_MESSAGE]         VARCHAR (4000) NULL,
    [INSERT_USER]           VARCHAR (100)  CONSTRAINT [DF_Log_INSERT_USER] DEFAULT (original_login()) NULL,
    [INSERT_TIME]           DATETIME2 (0)  CONSTRAINT [DF_Log_INSERT_TIME] DEFAULT (sysdatetime()) NULL,
    [LAST_UPDATE_USER]      VARCHAR (100)  NULL,
    [LAST_UPDATE_TIME]      DATETIME2 (0)  NULL,
    [INCREMENTAL_KEY_VALUE] VARCHAR (500)  NULL,
    PRIMARY KEY CLUSTERED ([LOG_ID] ASC)
);