CREATE TABLE [ETL].[SourceColumn] (
    [COLUMN_ID]                INT            IDENTITY (1, 1) NOT NULL,
    [SCHEMA_NAME]              NVARCHAR (150) NULL,
    [TABLE_NAME]               VARCHAR (150)  NOT NULL,
    [COLUMN_NAME]              NVARCHAR (150) NOT NULL,
    [PARQUET_COLUMN_NAME]      NVARCHAR (150) NULL,
    [COLUMN_DEFAULT]           NVARCHAR (150) NULL,
    [IS_NULLABLE]              NVARCHAR (150) NULL,
    [DATA_TYPE]                NVARCHAR (150) NULL,
    [CHARACTER_MAXIMUM_LENGTH] BIGINT         NULL,
    [COLLATION_NAME]           NVARCHAR (150) NULL,
    PRIMARY KEY CLUSTERED ([COLUMN_ID] ASC)
);