CREATE TABLE [ETL].[SQLTableMetadata] (
    [ID]                             INT           IDENTITY (1, 1) NOT NULL,
    [SOURCE_TYPE]                    VARCHAR (150) NOT NULL,
    [SOURCE_SYSTEM]                  VARCHAR (150) NOT NULL,
    [SOURCE_GROUPING_ID]             INT           NOT NULL,
    [IS_ENABLED]                     BIT           NOT NULL,
    [LOAD_TYPE]                      VARCHAR (100) NOT NULL,
    [BATCH_FREQUENCY]                VARCHAR (100) NOT NULL,
    [SOURCE_CONNECTION_STRING]       VARCHAR (500) NOT NULL,
    [DATABASE_NAME]                  VARCHAR (150) NOT NULL,
    [SCHEMA_NAME]                    VARCHAR (150) NULL,
    [TABLE_NAME]                     VARCHAR (150) NOT NULL,
    [PRIMARY_KEYS]                   VARCHAR (MAX) NULL,
    [WATERMARK_COLUMN]               VARCHAR (150) NULL,
    [SERVERLESS_SQL_POOL_DATABASE]   VARCHAR (100) NULL,
    [SERVERLESS_SQL_POOL_SCHEMA]     VARCHAR (100) NULL,
    [COLUMNS_LIST]                   VARCHAR (MAX) NULL,
    [COLUMNS_META]                   VARCHAR (MAX) NULL,
    [COLUMNS_META_CHANGE_TRACKING]   VARCHAR (MAX) NULL,
    [CHANGE_TRACKING_JOIN_CONDITION] VARCHAR (MAX) NULL,
    [INFORMATION_SCHEMA]             VARCHAR (MAX) NULL,
    [SCHEMA_VERSION]                 INT           NULL,
    [LAST_CHANGE_TRACKING_VALUE]     BIGINT        NULL,
    [LAST_WATERMARK_VALUE]           DATETIME2 (7) NULL
);

