
CREATE VIEW [ETL].[vw_LogRowCountsSummary] AS
SELECT
    r.[PIPELINE_RUN_ID]
    ,r.[SOURCE_SYSTEM]
    ,r.[TARGET_SYSTEM]
    ,r.[TABLE_NAME]
    ,r.[START_TIME]
    ,r.[SOURCE_SYSTEM_ROW_COUNT]
    ,r.[TARGET_SYSTEM_ROW_COUNT]
    ,[SOURCE_SYSTEM_ROW_COUNT] - [TARGET_SYSTEM_ROW_COUNT] as [ROW_COUNT_DELTA]
    ,CASE 
        WHEN [SOURCE_SYSTEM_ROW_COUNT] > 0 AND [TARGET_SYSTEM_ROW_COUNT] > 0 THEN CAST((CAST([TARGET_SYSTEM_ROW_COUNT] AS DECIMAL(18,5)) / CAST([SOURCE_SYSTEM_ROW_COUNT] AS DECIMAL(18,5))) AS decimal(8,5))*100
        WHEN [SOURCE_SYSTEM_ROW_COUNT] > 0 AND [TARGET_SYSTEM_ROW_COUNT] = 0 THEN 0      
    END AS [TARGET_ROW_COUNT_COVERAGE_(%)]
    ,CASE WHEN [SOURCE_SYSTEM_ROW_COUNT] = 0 AND [TARGET_SYSTEM_ROW_COUNT] = 0 THEN 'NA'
        WHEN  [SOURCE_SYSTEM_ROW_COUNT] - [TARGET_SYSTEM_ROW_COUNT] = 0 THEN 'PARITY' ELSE 'DISPARITY' 
    END AS [RESULT]

FROM [ETL].[LogRowCounts] AS r