
CREATE VIEW [ETL].[vw_LogRowCountsSummary] AS
SELECT [PIPELINE_RUN_ID]
    ,[SOURCE_SYSTEM]
    ,[TARGET_SYSTEM]
    ,[TABLE_NAME]
    ,[START_TIME]
    ,[SOURCE_SYSTEM_ROW_COUNT]
    ,[TARGET_SYSTEM_ROW_COUNT]
    ,[SOURCE_SYSTEM_ROW_COUNT] - [TARGET_SYSTEM_ROW_COUNT] as [ROW_COUNT_DELTA]
    ,CASE 
        WHEN [SOURCE_SYSTEM_ROW_COUNT] > 0 AND [TARGET_SYSTEM_ROW_COUNT] > 0 THEN CAST((CAST([TARGET_SYSTEM_ROW_COUNT] AS DECIMAL(18,5)) / CAST([SOURCE_SYSTEM_ROW_COUNT] AS DECIMAL(18,5))) AS decimal(8,5))*100
        WHEN [SOURCE_SYSTEM_ROW_COUNT] > 0 AND [TARGET_SYSTEM_ROW_COUNT] = 0 THEN 0      
    END AS [TARGET_ROW_COUNT_COVERAGE_(%)]
    ,CASE WHEN [SOURCE_SYSTEM_ROW_COUNT] = 0 AND [TARGET_SYSTEM_ROW_COUNT] = 0 THEN 'NA'
        WHEN  [SOURCE_SYSTEM_ROW_COUNT] - [TARGET_SYSTEM_ROW_COUNT] = 0 THEN 'PARITY' ELSE 'DISPARITY' 
    END AS [RESULT]

FROM [ETL].[LogRowCounts]
ORDER BY CAST([START_TIME] AS date) DESC, [SOURCE_SYSTEM], [TABLE_NAME]
OFFSET 0 ROWS