CREATE VIEW [ETL].[vw_SQLHighWatermarkLast28Days] AS
WITH cte_get_changes_copy_activity AS (
    SELECT [LOG_ID]
        ,[TRIGGERING_PIPELINE_RUN_ID]
        ,[SOURCE_SYSTEM]
        ,[OBJECT_NAME]
        ,[INSERTS]
        ,[UPDATES]
        ,[DELETES]
        ,[TRIGGER_TIME]
        ,[PREVIOUS_INCREMENTAL_KEY_VALUE]
    FROM [ETL].[Log]
    WHERE [COMPONENT_NAME] = 'copy_sql_to_raw_watermark'
    AND [TRIGGER_TIME] >= DATEADD(DAY,-28,GETDATE())
),

cte_get_changes_delta AS (
    SELECT [LOG_ID]
        ,[TRIGGERING_PIPELINE_RUN_ID]
        ,[SOURCE_SYSTEM]
        ,[OBJECT_NAME]
        ,[INSERTS]
        ,[UPDATES]
        ,[DELETES]
        ,[TRIGGER_TIME]
    FROM [ETL].[Log]
    WHERE [COMPONENT_NAME] = 'nb_lakehouse_orchestration_py'
    AND [TRIGGER_TIME] >= DATEADD(DAY,-28,GETDATE())
)

SELECT L.[SOURCE_SYSTEM]
    ,L.[DATABASE_NAME]
    ,L.[SCHEMA_NAME]
    ,L.[TABLE_NAME]
    ,L.[NEW_INCREMENTAL_KEY_VALUE] AS [NEW_WATERMARK_VALUE]
    ,CP.[PREVIOUS_INCREMENTAL_KEY_VALUE] AS [PREVIOUS_WATERMARK_VALUE]
    ,CP.[INSERTS] AS [TOTAL_ROWS_COPY]
    ,DT.[INSERTS] AS [INSERTS_DELTA]
    ,DT.[UPDATES] AS [UPDATES_DELTA]
    ,DT.[DELETES] AS [DELETES_DELTA]
    ,L.[LOG_ID] AS [LOG_ID_WATERMARK_UPDATE]
    ,CP.[LOG_ID] AS [LOG_ID_COPY]
    ,DT.[LOG_ID] AS [LOG_ID_DELTA]
    ,L.[TRIGGER_TIME] AS [LOG_TIME_WATERMARK_UPDATE]
    ,CP.[TRIGGER_TIME] AS [LOG_TIME_COPY]
    ,DT.[TRIGGER_TIME] AS [LOG_TIME_DELTA]
FROM [ETL].[Log] L
LEFT JOIN cte_get_changes_copy_activity CP
    ON L.[TRIGGERING_PIPELINE_RUN_ID] = CP.[TRIGGERING_PIPELINE_RUN_ID]
    AND L.[OBJECT_NAME] = CP.[OBJECT_NAME]
LEFT JOIN cte_get_changes_delta DT
    ON L.[TRIGGERING_PIPELINE_RUN_ID] = DT.[TRIGGERING_PIPELINE_RUN_ID]
    AND L.[OBJECT_NAME] = DT.[OBJECT_NAME]
WHERE L.[COMPONENT_NAME] = 'update_watermark'
AND L.[TRIGGER_TIME] >= DATEADD(DAY,-28,GETDATE())
ORDER BY L.[SOURCE_SYSTEM], L.[DATABASE_NAME], L.[SCHEMA_NAME], L.[TABLE_NAME], L.[TRIGGER_TIME] DESC
OFFSET 0 ROWS